- include: apt.yml

- name: Install nvm
  shell: |
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.5/install.sh | bash
  args:
    creates: ".nvm/nvm.sh"
    warn: false
  become: no


- name: Install node 8 and yarn
  shell: |
        source ~/.nvm/nvm.sh
        nvm install 8
        npm install -g yarn
  args:
    executable: /bin/bash
  become: no

- name: create IDE build/install dir
  file:
    path: "theia-ide"
    state: directory
  become: no

- name: copy IDE configuration
  copy:
    src: package.json
    dest: "theia-ide/package.json"
    mode: 0644
  become: no

- name: copy IDE start skript
  copy:
    src: theia-ide.sh
    dest: "theia-ide/theia-ide.sh"
    mode: 0755
  become: no

- name: build ide
  shell: |
        source ~/.nvm/nvm.sh
        yarn
        yarn theia build
  args:
    chdir: "theia-ide"
    executable: /bin/bash
  become: no

- name: Generate systemd service
  template:
    src: theia-ide.service.j2
    dest: /etc/systemd/system/theia-ide.service

- name: Enable and Start service
  systemd:
    name: theia-ide.service
    enabled: true
    state: started






